{% set name = "cogeo-mosaic" %}
{% set version = "7.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/cogeo_mosaic-{{ version }}.tar.gz
  sha256: fe5bcf16ab801d20a10bcf1ef6a1de913ff231c6a1c0c0ac0673925ffad4fc2e

build:
  number: 0
  noarch: python
  entry_points:
    - cogeo-mosaic = cogeo_mosaic.scripts.cli:cogeo_cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - hatchling
    - hatch-fancy-pypi-readme
    - python >=3.8
  run:
    - attrs
    - morecantile >=5.0,<6.0
    - shapely >=2.0,<3.0
    - pydantic
    - pydantic-settings
    - python >=3.8
    - httpx
    - rasterio
    - rio-tiler >=6.0,<7.0
    - supermorecado
    - cachetools
    - boto3
    - google-cloud-storage

test:
  imports:
    - cogeo_mosaic
    - cogeo_mosaic.backends
    - cogeo_mosaic.scripts.cli
  commands:
    - pip check
    - cogeo-mosaic --help
  requires:
    - pip

about:
  home: https://developmentseed.org/cogeo-mosaic
  summary: Create mosaicJSON.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/developmentseed/cogeo-mosaic.git

extra:
  recipe-maintainers:
    - andrewannex
    - lsetiawan
    - andrewannex
